pipeline {
    agent any

    environment {
        SERVICE_NAME = 'notification-service'
        IMAGE_NAME = 'student-task-pipeline-notification-service'
        DOCKER_HUB_USER = 'kp0705'
        KUBECONFIG = '/home/kartavya-patel/.kube/config'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                dir("services/${SERVICE_NAME}") {
                    sh 'npm install'
                }
            }
        }

        stage('Test') {
            steps {
                dir("services/${SERVICE_NAME}") {
                    sh 'npm test -- --passWithNoTests'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir("services/${SERVICE_NAME}") {
                    sh "docker build -t ${IMAGE_NAME}:latest ."
                }
            }
        }

        stage('Load Image to Minikube') {
            steps {
                sh "minikube image load ${IMAGE_NAME}:latest"
            }
        }

        stage('Ansible Deploy') {
            steps {
                sh '''

                    # Ensure we are using the minikube context
                    # Copy kubeconfig to workspace to avoid permission issues
                    mkdir -p .kube
                    cp $KUBECONFIG .kube/config
                    export KUBECONFIG=$(pwd)/.kube/config

                    kubectl config use-context minikube

                    # Apply manifests via Ansible Playbook
                    ansible-playbook ansible/playbooks/k8s-deploy.yml --vault-password-file .vault_pass -e "target_dir=k8s/${SERVICE_NAME}/" -e "service_name=${SERVICE_NAME}"
                '''
            }
        }
    }

    post {
        success {
            emailext(
                to: "kpbhai0705@gmail.com",
                subject: "SUCCESS: ${currentBuild.fullDisplayName}",
                body: "The deployment was successful. Check logs at ${env.BUILD_URL}"
            )
            echo "${SERVICE_NAME} deployed successfully!"
        }
        failure {
            emailext(
                to: "kpbhai0705@gmail.com",
                subject: "FAILURE: ${currentBuild.fullDisplayName}",
                body: "The deployment failed. Check logs at ${env.BUILD_URL}"
            )
            echo "${SERVICE_NAME} deployment failed!"
        }
    }
}
