pipeline {
    agent any

    environment {
        SERVICE_NAME = 'analytics-service'
        IMAGE_NAME = 'student-task-pipeline-analytics-service'
        DOCKER_HUB_USER = 'kp0705'
        KUBECONFIG = '/home/kartavya-patel/.kube/config'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                dir("services/${SERVICE_NAME}") {
                    sh 'npm install'
                }
            }
        }

        stage('Test') {
            steps {
                dir("services/${SERVICE_NAME}") {
                    sh 'npm test -- --passWithNoTests'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir("services/${SERVICE_NAME}") {
                    sh "docker build -t ${IMAGE_NAME}:latest ."
                }
            }
        }

        stage('Load Image to Minikube') {
            steps {
                sh "minikube image load ${IMAGE_NAME}:latest"
            }
        }

        stage('Kubernetes Deploy') {
            steps {
                sh '''

                    # Ensure we are using the minikube context
                    kubectl config use-context minikube

                    # Apply manifests
                    kubectl apply -f k8s/${SERVICE_NAME}/ --validate=false
                    kubectl rollout status deployment/${SERVICE_NAME} -n studyos --timeout=120s
                '''
            }
        }
    }

    post {
        success {
            mail to: "kp0705@gmail.com",
                 subject: "SUCCESS: ${currentBuild.fullDisplayName}",
                 body: "The deployment was successful. Check logs at ${env.BUILD_URL}"
            echo "${SERVICE_NAME} deployed successfully!"
        }
        failure {
            mail to: "kp0705@gmail.com",
                 subject: "FAILURE: ${currentBuild.fullDisplayName}",
                 body: "The deployment failed. Check logs at ${env.BUILD_URL}"
            echo "${SERVICE_NAME} deployment failed!"
        }
    }
}
