pipeline {
    agent any

    environment {
        SERVICE_NAME = 'auth-service'
        IMAGE_NAME = 'student-task-pipeline-auth-service'
        DOCKER_HUB_USER = 'kp0705'
        KUBECONFIG = '/home/kartavya-patel/.kube/config'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                dir("services/${SERVICE_NAME}") {
                    sh 'npm install'
                }
            }
        }

        stage('Test') {
            steps {
                dir("services/${SERVICE_NAME}") {
                    sh 'npm test -- --passWithNoTests'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir("services/${SERVICE_NAME}") {
                    sh "docker build -t ${IMAGE_NAME}:latest ."
                }
            }
        }

        stage('Load Image to Minikube') {
            steps {
                sh "minikube image load ${IMAGE_NAME}:latest"
            }
        }

        stage('Ansible Deploy') {
            steps {
                sh '''
                    # Copy kubeconfig to workspace and flatten all certs inline
                    # This avoids jenkins user hitting permission denied on ~/.minikube certs
                    mkdir -p .kube
                    KUBECONFIG=/home/kartavya-patel/.kube/config kubectl config view --flatten > .kube/config
                    chmod 600 .kube/config
                    export KUBECONFIG=$(pwd)/.kube/config

                    kubectl config use-context minikube

                    # Apply manifests via Ansible Playbook, overriding kubeconfig_path with the workspace copy
                    ansible-playbook ansible/playbooks/k8s-deploy.yml \
                        --vault-password-file .vault_pass \
                        -e "target_dir=k8s/${SERVICE_NAME}/" \
                        -e "service_name=${SERVICE_NAME}" \
                        -e "kubeconfig_path=$(pwd)/.kube/config"
                '''
            }
        }
    }

    post {

    success {
        emailext(
            to: "kpbhai0705@gmail.com",
            subject: "SUCCESS: ${currentBuild.fullDisplayName}",
            body: """
                 Deployment successful.
                 Job: ${env.JOB_NAME}
                 Build Number: ${env.BUILD_NUMBER}
                 Check logs:
                ${env.BUILD_URL}
                    """ )
        echo "${SERVICE_NAME} deployed successfully!"
            }
    failure {
        emailext(
            to: "kpbhai0705@gmail.com",
            subject: "FAILURE: ${currentBuild.fullDisplayName}",
            body: """
         Deployment failed.
         Job: ${env.JOB_NAME}
         Build Number: ${env.BUILD_NUMBER}
        Check logs:
        ${env.BUILD_URL}
        """
        )
        echo "${SERVICE_NAME} deployment failed!"
            }
       }

}
